version: '3.9'

services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-gitlab-hooks-listener-container
    restart: always
    volumes:
      - ./:/var/www/html/api
    ports:
      - "59681:59681"
    command: >
     bash -c "./scripts/build.sh && ./scripts/run.sh"
    dns:
      - 8.8.8.8