http-server :
  port: 59681
  token: hm3RxQ9PN6nN22fXwlXqvJzDtDGsuue3n0CIUP25Ve9cfUoSscuLVUAthNx3ZvHp

telegram :
  token : your-telegram-bot-token
  chat : your-chat-id-token

hooks-events: 
  repository: true 
  push: true 
  tag-push: true 
  merege-request: true